#! /usr/bin/bash

function listMainMenu(){
    echo "Main Menu:"
    echo "Select a database operation by number:"
    echo "1. Create Database"
    echo "2. List Databases"
    echo "3. Connect to Database"
    echo "4. Drop Database"
    echo "5. Exit"
    echo -n "Enter your choice: "
}