#!/bin/bash
shopt -s extglob
trap "echo -e '\nSeems like you tried to force cancel. Returning to main menu.'; exit" SIGINT SIGTERM
while true
do
	read -p "Enter the name of the table you want to delete: " tablename
	
	if [[ -f "$tablename" ]]
	then

			read -p "Are you sure you want to delete this table? [Yes][No]: " decision
			if [[ "$decision" =~ ^[Yy][eE][sS]$ ]]
			then
				rm -f "$tablename"
				echo "table '$tablename' deleted successfully...here is the new list of tables: "
				ls
				break
			fi
			if [[ "$decision" =~ ^[nN][oO]$ ]]
			then
				read -p $'\nNo table was deleted.\nWould you like to:\n\
				[1] Try again\n\
				[2] Exit to main menu (not implemented)\n\
				Enter option: ' option	
				case $option in
					"1")
						continue
						;;
					
					"2")
						echo "Going back to main menu..."
						break
						;;
					
					*)
						echo "invalid input"
						break
					       	;;
				esac		
				
			fi
		else
		echo "No table found with this name, Here's a list of the existing tables: "
		ls
		continue

	fi



done
