#!/usr/bin/bash

FILE_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"

while true 
do
    echo "Connecting to a database one of them..."
    ls -F "$DB_DIR" 
    if ! ls -F "$DB_DIR" > /dev/null 2>&1
    then
        echo "No databases found. Please create a database first."
        break
    fi
    read -p "Enter the name of the database you want to connect to or "exit" to exist: " db_name

    if [[ $db_name =~ ^[eE][xX][iI][tT]$ ]]
	then
			echo "Ending session..."
			break
	fi
    if [ -d $DB_DIR/$db_name ]
    then
        echo "Connected to database: $db_name"
        . "$FILE_DIR/../table_operations/menu.sh"  $db_name
    else
        echo "Database $db_name does not exist. Please create it first."
        continue
    fi  
done