#! /usr/bin/bash

ls -F ~/dbs
if [ $? -ne 0 ]; then
    echo "No databases found Please create a database first."
    exit 1
fi
read -p "Enter the name of the database you want to drop: " db_name

if [ -d ~/dbs/$db_name ]; then
    rm -rf ~/dbs/$db_name
    echo "Database $db_name has been dropped successfully."
    cd $1
else
    echo "Database $db_name does not exist. Please check the name and try again."
fi  