#! /usr/bin/bash

ls -F $DB_DIR
if [ $? -ne 0 ]
then
    echo "No databases found Please create a database first."
    
fi
while true
    do
    read -p 'Enter the name of the database you want to drop or enter "exit" to quit: ' db_name
    if [[ $db_name =~ ^[eE][xX][iI][tT]$ ]]
	then
			echo "Ending session..."
			break
	fi
    if [ -d $DB_DIR/$db_name ]
    then
        read -p "Are you sure you want to delete this table? [Yes][No]: " decision
        if [[ "$decision" =~ ^[Yy][eE][sS]$ ]]
        then
            rm -rf $DB_DIR/$db_name
            echo "Database $db_name has been dropped successfully."
        break
        elif [[ "$decision" =~ ^[nN][oO]$ ]]
        then
            continue
        fi
    else
        echo "Database $db_name does not exist. Please check the name and try again."
    fi  
done