#! /usr/bin/bash

echo "Listing all databases..."
ls -F $DB_DIR 
echo "---------------------------------------------"
if [ $? -ne 0 ]
then
    echo "No databases found. Please create a database first."

fi